/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CrateInfoRouteImport } from './routes/crate-info'
import { Route as AuthenticatedCrateKnowsRouteImport } from './routes/_authenticated/crate-knows'
import { Route as AuthenticatedStudioRouteImport } from './routes/_authenticated/studio'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as AuthenticatedAdminBugsRouteImport } from './routes/_authenticated/admin.bugs'
import { Route as AuthenticatedAdminMemoryRouteImport } from './routes/_authenticated/admin.memory'
import { Route as AuthenticatedAdminNotepadRouteImport } from './routes/_authenticated/admin.notepad'
import { Route as ApiPublicSpotifyCallbackRouteImport } from './routes/api/public/spotify/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CrateInfoRoute = CrateInfoRouteImport.update({
  id: '/crate-info',
  path: '/crate-info',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCrateKnowsRoute = AuthenticatedCrateKnowsRouteImport.update({
  id: '/crate-knows',
  path: '/crate-knows',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudioRoute = AuthenticatedStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminBugsRoute = AuthenticatedAdminBugsRouteImport.update({
  id: '/admin/bugs',
  path: '/admin/bugs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminMemoryRoute =
  AuthenticatedAdminMemoryRouteImport.update({
    id: '/admin/memory',
    path: '/admin/memory',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminNotepadRoute =
  AuthenticatedAdminNotepadRouteImport.update({
    id: '/admin/notepad',
    path: '/admin/notepad',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicSpotifyCallbackRoute =
  ApiPublicSpotifyCallbackRouteImport.update({
    id: '/api/public/spotify/callback',
    path: '/api/public/spotify/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/crate-info': typeof CrateInfoRoute
  '/crate-knows': typeof AuthenticatedCrateKnowsRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/api/chat': typeof ApiChatRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/admin/bugs': typeof AuthenticatedAdminBugsRoute
  '/admin/memory': typeof AuthenticatedAdminMemoryRoute
  '/admin/notepad': typeof AuthenticatedAdminNotepadRoute
  '/api/public/spotify/callback': typeof ApiPublicSpotifyCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/crate-info': typeof CrateInfoRoute
  '/crate-knows': typeof AuthenticatedCrateKnowsRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/api/chat': typeof ApiChatRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/admin/bugs': typeof AuthenticatedAdminBugsRoute
  '/admin/memory': typeof AuthenticatedAdminMemoryRoute
  '/admin/notepad': typeof AuthenticatedAdminNotepadRoute
  '/api/public/spotify/callback': typeof ApiPublicSpotifyCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/crate-info': typeof CrateInfoRoute
  '/_authenticated/crate-knows': typeof AuthenticatedCrateKnowsRoute
  '/_authenticated/studio': typeof AuthenticatedStudioRoute
  '/api/chat': typeof ApiChatRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/_authenticated/admin/bugs': typeof AuthenticatedAdminBugsRoute
  '/_authenticated/admin/memory': typeof AuthenticatedAdminMemoryRoute
  '/_authenticated/admin/notepad': typeof AuthenticatedAdminNotepadRoute
  '/api/public/spotify/callback': typeof ApiPublicSpotifyCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/crate-info'
    | '/crate-knows'
    | '/studio'
    | '/api/chat'
    | '/api/transcribe'
    | '/admin/bugs'
    | '/admin/memory'
    | '/admin/notepad'
    | '/api/public/spotify/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/crate-info'
    | '/crate-knows'
    | '/studio'
    | '/api/chat'
    | '/api/transcribe'
    | '/admin/bugs'
    | '/admin/memory'
    | '/admin/notepad'
    | '/api/public/spotify/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/crate-info'
    | '/_authenticated/crate-knows'
    | '/_authenticated/studio'
    | '/api/chat'
    | '/api/transcribe'
    | '/_authenticated/admin/bugs'
    | '/_authenticated/admin/memory'
    | '/_authenticated/admin/notepad'
    | '/api/public/spotify/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CrateInfoRoute: typeof CrateInfoRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  ApiPublicSpotifyCallbackRoute: typeof ApiPublicSpotifyCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crate-info': {
      id: '/crate-info'
      path: '/crate-info'
      fullPath: '/crate-info'
      preLoaderRoute: typeof CrateInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/crate-knows': {
      id: '/_authenticated/crate-knows'
      path: '/crate-knows'
      fullPath: '/crate-knows'
      preLoaderRoute: typeof AuthenticatedCrateKnowsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio': {
      id: '/_authenticated/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof AuthenticatedStudioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/bugs': {
      id: '/_authenticated/admin/bugs'
      path: '/admin/bugs'
      fullPath: '/admin/bugs'
      preLoaderRoute: typeof AuthenticatedAdminBugsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/memory': {
      id: '/_authenticated/admin/memory'
      path: '/admin/memory'
      fullPath: '/admin/memory'
      preLoaderRoute: typeof AuthenticatedAdminMemoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/notepad': {
      id: '/_authenticated/admin/notepad'
      path: '/admin/notepad'
      fullPath: '/admin/notepad'
      preLoaderRoute: typeof AuthenticatedAdminNotepadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/spotify/callback': {
      id: '/api/public/spotify/callback'
      path: '/api/public/spotify/callback'
      fullPath: '/api/public/spotify/callback'
      preLoaderRoute: typeof ApiPublicSpotifyCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCrateKnowsRoute: typeof AuthenticatedCrateKnowsRoute
  AuthenticatedStudioRoute: typeof AuthenticatedStudioRoute
  AuthenticatedAdminBugsRoute: typeof AuthenticatedAdminBugsRoute
  AuthenticatedAdminMemoryRoute: typeof AuthenticatedAdminMemoryRoute
  AuthenticatedAdminNotepadRoute: typeof AuthenticatedAdminNotepadRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCrateKnowsRoute: AuthenticatedCrateKnowsRoute,
  AuthenticatedStudioRoute: AuthenticatedStudioRoute,
  AuthenticatedAdminBugsRoute: AuthenticatedAdminBugsRoute,
  AuthenticatedAdminMemoryRoute: AuthenticatedAdminMemoryRoute,
  AuthenticatedAdminNotepadRoute: AuthenticatedAdminNotepadRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CrateInfoRoute: CrateInfoRoute,
  ApiChatRoute: ApiChatRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  ApiPublicSpotifyCallbackRoute: ApiPublicSpotifyCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
